It's a Python-based scientific computing package targeted at two sets of audiences:
   * a replacement for Numpy to use the power of GPUs
   * a deep learning research platform that provides maximum flexibility and speed

# Getting Started

## Tensors

Tensors are similiar to Numpy's ndarrays, with the addition being that Tensors can also be used on a GPU to accelerate computing.

In [1]:
import torch

* Note 

   An uninitialized matrix is declared, but does not contain definite known values before it is used. When an uninitialized matrix is created, whatever values were in the allocated memory at the time will appear as the initial values.
   
Construct a 5x3 matrix, uninitialized:

In [2]:
x = torch.empty(5, 3)
print(x)

tensor([[2.7517e+12, 7.5338e+28, 3.0313e+32],
        [6.3828e+28, 1.4603e-19, 1.0899e+27],
        [6.8943e+34, 1.1835e+22, 7.0976e+22],
        [1.8515e+28, 4.1988e+07, 3.0357e+32],
        [2.7224e+20, 7.7782e+31, 4.7429e+30]])


Construct a randomly initialized matrix:

In [3]:
x = torch.rand(5, 3)
print(x)

tensor([[0.7653, 0.0161, 0.3200],
        [0.3272, 0.3065, 0.0430],
        [0.7627, 0.1586, 0.7239],
        [0.4871, 0.5731, 0.9479],
        [0.5558, 0.2342, 0.6044]])


Construct a matrix filled zeros and of dtype long:

In [5]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


Construct a tensor directly from data:

In [9]:
x = torch.tensor([5, 3])
print(x)

import numpy as np
x = torch.from_numpy(np.array([5, 3]))
print(x)

tensor([5, 3])
tensor([5, 3])


or create a tensor based on an existing tensor. These methods will reuse properties of the input tensor, e.g. dtype, unless new values are provided by user

In [10]:
x = x.new_ones(5, 3, dtype = torch.double)
print(x)

x = torch.randn_like(x, dtype=torch.double)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[ 0.9151,  1.4192, -0.8819],
        [-0.5248,  0.4762, -0.2422],
        [ 1.2609, -0.2316, -1.2126],
        [-0.0180,  0.5316, -1.8198],
        [-0.9683, -0.1153, -0.6758]], dtype=torch.float64)


Get its size:

In [12]:
print(x.size())

torch.Size([5, 3])


* Note

   *torch.Size* is in fact a tuple, so it supports all tuple operations.
   
## Operations

There are multiple syntaxes for operations. In the following example, we will take a look at the addition operation.

Addition: syntax 1

In [14]:
y = torch.rand(5, 3, dtype=torch.double)
print(x + y)

tensor([[ 1.0927,  1.9494, -0.3493],
        [ 0.0851,  1.1857, -0.0265],
        [ 1.5745,  0.6357, -1.0777],
        [ 0.4108,  0.8239, -1.2058],
        [-0.7224,  0.5053, -0.2948]], dtype=torch.float64)


Addition: syntax 2

In [15]:
print(torch.add(x, y))

tensor([[ 1.0927,  1.9494, -0.3493],
        [ 0.0851,  1.1857, -0.0265],
        [ 1.5745,  0.6357, -1.0777],
        [ 0.4108,  0.8239, -1.2058],
        [-0.7224,  0.5053, -0.2948]], dtype=torch.float64)


Addition: providing an output tensor as argument

In [16]:
z = torch.empty(5, 3, dtype=torch.double)
torch.add(x, y, out=z)
print(z)

tensor([[ 1.0927,  1.9494, -0.3493],
        [ 0.0851,  1.1857, -0.0265],
        [ 1.5745,  0.6357, -1.0777],
        [ 0.4108,  0.8239, -1.2058],
        [-0.7224,  0.5053, -0.2948]], dtype=torch.float64)


Addition: in-place

In [17]:
y.add_(x)
print(y)

tensor([[ 1.0927,  1.9494, -0.3493],
        [ 0.0851,  1.1857, -0.0265],
        [ 1.5745,  0.6357, -1.0777],
        [ 0.4108,  0.8239, -1.2058],
        [-0.7224,  0.5053, -0.2948]], dtype=torch.float64)


* Note

   Any operation that mutates a tensor in-place is post-fixed with an \_.
   For example: *x.copy_(y)*, *x.t_()*, will change *x*.
   
You can use standard NumPy-like indexing with all bells and whistles!

In [18]:
print(y[0])
print(y[:, 1])

tensor([ 1.0927,  1.9494, -0.3493], dtype=torch.float64)
tensor([1.9494, 1.1857, 0.6357, 0.8239, 0.5053], dtype=torch.float64)


Resizing: If you want to resize/reshape tensor, you can use *torch.view*:

In [19]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)
print(x.shape, y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


If you have a one element tensor, use *.item()* to get the value as a Python number

In [21]:
print(x)
print(x[0][0].item())

tensor([[-1.1985, -0.3460, -1.4693,  0.8942],
        [ 0.1433,  0.0478, -0.0407,  0.7209],
        [-1.8723, -1.1513,  0.1680, -0.9314],
        [-1.0251, -0.2872, -0.4302, -0.4451]])
-1.1985353231430054


* Read later:

   100+ Tensor operations, including transposing, indexing, slicing, mathematical operations, linear algebra, random numbers, etc., are described [here](https://pytorch.org/docs/torch).
  
## NumPy Bridge

Converting a Torch Tensor to a NumPy array and vice versa is a breeze.

The Torch Tensor and NumPy array will share their underlying memory locations (if the Torch Tensor is on CPU), and changing one will change the other.

### Converting a Torch Tensor to a NumPy Array

In [22]:
x = torch.ones([2, 3, 4])
print(x)

y = x.numpy()
print(y)

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])
[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


See how the numpy array changed in value.

In [23]:
x.add_(1)
print(x)
print(y)

tensor([[[2., 2., 2., 2.],
         [2., 2., 2., 2.],
         [2., 2., 2., 2.]],

        [[2., 2., 2., 2.],
         [2., 2., 2., 2.],
         [2., 2., 2., 2.]]])
[[[2. 2. 2. 2.]
  [2. 2. 2. 2.]
  [2. 2. 2. 2.]]

 [[2. 2. 2. 2.]
  [2. 2. 2. 2.]
  [2. 2. 2. 2.]]]


### Converting NumPy Array to Torch Tensor

See how changing the np array changed the Torch Tensor automatically

In [27]:
x = np.ones([2, 3, 4])
print(x)

y = torch.from_numpy(x)
print(y)

x = np.add(x, 1, out=x)
print(x)
print(y)

x = np.add(x, 1)
print(x)
print(y)

[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]
tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]], dtype=torch.float64)
[[[2. 2. 2. 2.]
  [2. 2. 2. 2.]
  [2. 2. 2. 2.]]

 [[2. 2. 2. 2.]
  [2. 2. 2. 2.]
  [2. 2. 2. 2.]]]
tensor([[[2., 2., 2., 2.],
         [2., 2., 2., 2.],
         [2., 2., 2., 2.]],

        [[2., 2., 2., 2.],
         [2., 2., 2., 2.],
         [2., 2., 2., 2.]]], dtype=torch.float64)
[[[3. 3. 3. 3.]
  [3. 3. 3. 3.]
  [3. 3. 3. 3.]]

 [[3. 3. 3. 3.]
  [3. 3. 3. 3.]
  [3. 3. 3. 3.]]]
tensor([[[2., 2., 2., 2.],
         [2., 2., 2., 2.],
         [2., 2., 2., 2.]],

        [[2., 2., 2., 2.],
         [2., 2., 2., 2.],
         [2., 2., 2., 2.]]], dtype=torch.float64)


All the Tensors on the CPU except a CharTensor support converting to NumPy and back.

### CUDA Tensors

Tensors can be moved onto any device using the .to method.

In [28]:
x = torch.zeros([2, 3])

if torch.cuda.is_available():
    device = torch.device("cuda")
    y = torch.ones_like(x, device=device)
    x = x.to(device)
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))

tensor([[1., 1., 1.],
        [1., 1., 1.]], device='cuda:0')
tensor([[1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
